// Copyright (c) 2026 LingByte. All rights reserved.
// SPDX-License-Identifier: MIT

// Package registry provides service registration and discovery for
// microservice architectures. It defines a framework-agnostic
// [Registry] interface and ships a Consul implementation.
//
// # Quick start (Consul)
//
//	reg, err := consul.New(consul.Config{
//	    Address: "127.0.0.1:8500",
//	})
//	if err != nil { ... }
//	defer reg.Close()
//
//	// Register a service instance.
//	inst := registry.Instance{
//	    ServiceName: "order-service",
//	    ID:          "order-1",
//	    Host:        "10.0.0.5",
//	    Port:        8080,
//	    Tags:        []string{"v1", "primary"},
//	    HealthPath:  "/health",
//	}
//	if err := reg.Register(inst); err != nil { ... }
//
//	// Discover service instances.
//	instances, err := reg.Discover("order-service")
//	if err != nil { ... }
//
//	// Deregister on shutdown.
//	reg.Deregister("order-1")
//
// # Custom implementations
//
// Implement the [Registry] interface to support Nacos, etcd, ZooKeeper,
// or any other service-discovery backend.
package registry

import (
	"context"
	"errors"
	"time"
)

// ──────────────────────────────────────────────
// Errors
// ──────────────────────────────────────────────

var (
	// ErrNotFound is returned when no instances are found for a service.
	ErrNotFound = errors.New("registry: service not found")
	// ErrAlreadyRegistered is returned when registering an instance
	// that is already registered (optional, implementations may
	// upsert instead).
	ErrAlreadyRegistered = errors.New("registry: instance already registered")
	// ErrNotRegistered is returned when deregistering an unknown ID.
	ErrNotRegistered = errors.New("registry: instance not registered")
	// ErrClosed is returned when operating on a closed registry.
	ErrClosed = errors.New("registry: closed")
)

// ──────────────────────────────────────────────
// Data types
// ──────────────────────────────────────────────

// Instance describes a single service instance registered with the
// service-discovery backend.
type Instance struct {
	// ServiceName is the logical name of the service (e.g. "order-service").
	ServiceName string

	// ID is the unique identifier for this instance (e.g. "order-1").
	// If empty, a unique ID should be generated by the implementation.
	ID string

	// Host is the IP address or hostname of the instance.
	Host string

	// Port is the port the instance listens on.
	Port int

	// Tags are optional labels (e.g. ["v1", "primary", "us-east"]).
	Tags []string

	// HealthPath is the HTTP health-check path (e.g. "/health").
	// If empty, the implementation may use a TCP check instead.
	HealthPath string

	// HealthInterval is the health-check interval.
	// If zero, the implementation default is used.
	HealthInterval time.Duration

	// HealthTimeout is the health-check timeout.
	// If zero, the implementation default is used.
	HealthTimeout time.Duration

	// Meta is arbitrary metadata attached to the instance.
	Meta map[string]string
}

// Address returns "host:port" for this instance.
func (i Instance) Address() string {
	return formatAddress(i.Host, i.Port)
}

// ──────────────────────────────────────────────
// Registry interface
// ──────────────────────────────────────────────

// Registry is the abstraction for service registration and discovery.
// Implementations may be Consul, Nacos, etcd, ZooKeeper, or an
// in-memory store for testing.
type Registry interface {
	// Register registers a service instance.
	Register(ctx context.Context, inst Instance) error

	// Deregister removes a service instance by ID.
	Deregister(ctx context.Context, instanceID string) error

	// Discover returns all healthy instances for a service name.
	Discover(ctx context.Context, serviceName string) ([]Instance, error)

	// Watch returns a channel that receives updated instance lists
	// whenever the service's membership changes. The channel is
	// closed when ctx is canceled. Implementations that do not
	// support watch may return an error.
	Watch(ctx context.Context, serviceName string) (<-chan []Instance, error)

	// Close releases all resources (deregisters all instances
	// registered through this registry, if applicable).
	Close() error
}

// ──────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────

func formatAddress(host string, port int) string {
	return host + ":" + itoa(port)
}

// itoa is a dependency-free int-to-string converter.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
