// Copyright (c) 2026 LingByte. All rights reserved.
// SPDX-License-Identifier: MIT

// Package auditlog provides a pluggable audit-logging facility. It records
// who did what to which resource, when, and from where, and supports
// querying historical entries through a storage backend.
//
// The storage backend is abstracted by the [Storage] interface so that
// concrete implementations (SQL, NoSQL, file, etc.) can be plugged in.
// An in-memory implementation ([MemoryStorage]) is provided for testing
// and simple in-process use.
//
// # Quick start
//
//	store := auditlog.NewMemoryStorage()
//	logger := auditlog.NewLogger(store)
//
//	err := logger.LogAction(ctx, "user-1", "login", "session", "sess-9",
//	    auditlog.WithIP("10.0.0.1"),
//	    auditlog.WithStatus("success"),
//	)
package auditlog

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"sync"
	"time"
)

// Entry represents a single audit-log record.
type Entry struct {
	// ID is a unique identifier auto-generated by the logger when empty.
	ID string
	// Timestamp is when the event occurred; auto-set by the logger when zero.
	Timestamp time.Time
	// UserID is the actor performing the action.
	UserID string
	// Action is the verb describing what was done (e.g. "create", "login").
	Action string
	// Resource is the type of resource acted upon (e.g. "user", "order").
	Resource string
	// ResourceID is the identifier of the specific resource instance.
	ResourceID string
	// IP is the client IP address, if known.
	IP string
	// UserAgent is the client User-Agent string, if known.
	UserAgent string
	// Status is the outcome, e.g. "success" or "failure".
	Status string
	// Detail is an optional bag of extra structured information.
	Detail map[string]any
	// RequestID correlates the audit entry with a request trace.
	RequestID string
}

// Filter specifies query criteria for retrieving audit entries.
type Filter struct {
	// UserID filters by actor. Empty means any.
	UserID string
	// Action filters by action verb. Empty means any.
	Action string
	// Resource filters by resource type. Empty means any.
	Resource string
	// StartTime, if non-nil, excludes entries before this time.
	StartTime *time.Time
	// EndTime, if non-nil, excludes entries after this time.
	EndTime *time.Time
	// Limit caps the number of returned entries. <=0 means a sane default.
	Limit int
}

// Storage is the persistence backend for audit entries.
type Storage interface {
	// Save persists a single entry.
	Save(ctx context.Context, entry *Entry) error
	// Query returns entries matching the filter, newest-first when the
	// backend supports ordering.
	Query(ctx context.Context, filter *Filter) ([]*Entry, error)
}

// LogOption is an optional parameter for [Logger.LogAction].
type LogOption func(*Entry)

// WithIP sets the IP field on the entry.
func WithIP(ip string) LogOption {
	return func(e *Entry) { e.IP = ip }
}

// WithUserAgent sets the UserAgent field on the entry.
func WithUserAgent(ua string) LogOption {
	return func(e *Entry) { e.UserAgent = ua }
}

// WithDetail sets the Detail field on the entry. The map is used as-is.
func WithDetail(detail map[string]any) LogOption {
	return func(e *Entry) { e.Detail = detail }
}

// WithStatus sets the Status field on the entry.
func WithStatus(status string) LogOption {
	return func(e *Entry) { e.Status = status }
}

// WithRequestID sets the RequestID field on the entry.
func WithRequestID(id string) LogOption {
	return func(e *Entry) { e.RequestID = id }
}

// Logger records audit entries to a [Storage] backend.
type Logger struct {
	storage Storage
}

// NewLogger returns a new [Logger] backed by the given storage.
func NewLogger(storage Storage) *Logger {
	return &Logger{storage: storage}
}

// Log records a single entry. If entry.ID is empty a random UUID-like ID
// is generated. If entry.Timestamp is zero the current time is used.
func (l *Logger) Log(ctx context.Context, entry *Entry) error {
	if l == nil || l.storage == nil {
		return errors.New("auditlog: logger not initialized")
	}
	if entry == nil {
		return errors.New("auditlog: entry is nil")
	}
	if entry.ID == "" {
		id, err := newID()
		if err != nil {
			return fmt.Errorf("auditlog: generate id: %w", err)
		}
		entry.ID = id
	}
	if entry.Timestamp.IsZero() {
		entry.Timestamp = time.Now()
	}
	return l.storage.Save(ctx, entry)
}

// LogAction is a convenience wrapper that builds an [Entry] from the
// required fields, applies the given options, and records it.
func (l *Logger) LogAction(ctx context.Context, userID, action, resource, resourceID string, opts ...LogOption) error {
	entry := &Entry{
		UserID:     userID,
		Action:     action,
		Resource:   resource,
		ResourceID: resourceID,
	}
	for _, opt := range opts {
		opt(entry)
	}
	return l.Log(ctx, entry)
}

// newID returns a random 128-bit hex string (a v4-style UUID without
// hyphens) generated from crypto/rand.
func newID() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	// RFC 4122 v4 variant bits, not strictly necessary for audit IDs but
	// keeps the format consistent with UUIDs.
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return hex.EncodeToString(b[:]), nil
}

// MemoryStorage is an in-memory [Storage] implementation suitable for
// testing and simple in-process use. It is safe for concurrent use.
type MemoryStorage struct {
	mu      sync.Mutex
	entries []*Entry
}

// NewMemoryStorage returns a new empty [MemoryStorage].
func NewMemoryStorage() *MemoryStorage {
	return &MemoryStorage{}
}

// Save appends the entry to the in-memory store.
func (s *MemoryStorage) Save(_ context.Context, entry *Entry) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.entries = append(s.entries, entry)
	return nil
}

// Query returns entries matching the filter, ordered newest-first.
func (s *MemoryStorage) Query(_ context.Context, filter *Filter) ([]*Entry, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	limit := 0
	if filter != nil {
		limit = filter.Limit
	}
	if limit <= 0 {
		limit = len(s.entries)
	}

	out := make([]*Entry, 0, limit)
	// Iterate newest-first.
	for i := len(s.entries) - 1; i >= 0 && len(out) < limit; i-- {
		e := s.entries[i]
		if filter != nil && !matchFilter(e, filter) {
			continue
		}
		out = append(out, e)
	}
	return out, nil
}

// matchFilter reports whether e satisfies all non-zero fields of f.
func matchFilter(e *Entry, f *Filter) bool {
	if f.UserID != "" && e.UserID != f.UserID {
		return false
	}
	if f.Action != "" && e.Action != f.Action {
		return false
	}
	if f.Resource != "" && e.Resource != f.Resource {
		return false
	}
	if f.StartTime != nil && e.Timestamp.Before(*f.StartTime) {
		return false
	}
	if f.EndTime != nil && e.Timestamp.After(*f.EndTime) {
		return false
	}
	return true
}
